server:
  port: 81

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 47.93.60.69
      port: 8500
      discovery:
        service-name: ${spring.application.name}


