server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyucui1002926/springcloud-config.git
          ##搜索目录.这个目录指的是github上的目录
          #          search-paths:
          #            - config-repo
          label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/