server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 47.93.60.69
      port: 8500
      discovery:
        service-name:  ${spring.application.name}